version = '2'

[run]
allow-parallel-runners = true

[issues]
max-same-issues = 0

[linters]
default = 'all'
disable = [
	'depguard',     # not yet
	'nlreturn',     # lolwut
	'noinlineerr',  # lolwut
	'paralleltest', # t.Parallel isn't what you think it is
	'varnamelen',   # false positives on `id` and iteration/index vars
	'wsl_v5',       # too aesthetic

	'exhaustruct', # deprecated
	'gomodguard',  # deprecated
	'wsl',         # deprecated
]

[linters.settings]
[linters.settings.errcheck]
check-type-assertions = true
check-blank = true

[linters.settings.funlen]
lines = -1

[linters.settings.nolintlint]
require-explanation = true
require-specific = true

[linters.settings.exhaustruct_v5]
allow-empty = true
allow-empty-returns = true
allow-empty-declarations = true

[linters.exclusions]
generated = 'strict'
paths = ['vendor']

[formatters]
enable = ['gci', 'gofmt', 'gofumpt', 'goimports']

[formatters.settings]
[formatters.settings.gofumpt.extra]
group-params = true

[formatters.exclusions]
generated = 'lax'
paths = ['vendor']
